---
output: 
  word_document:
    reference_docx: ..\PFA_report_template_v1.4.dotx
---

```{r setup, include=FALSE}

################################################################################
# EqSim Summarize_SS.Rmd
#
# 06/07/2020 tested on 1000 iters of SAM assessment
# 05/08/2020 converted to Rmd file
#
################################################################################

require("knitr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, crop = TRUE, comment = "")
knitr::opts_chunk$set(fig.width=10) 

options(dplyr.summarise.inform = FALSE)


# rm(list=ls())
invisible(gc())

library(FLCore)
library(tidyverse)


Base.dir <- dirname(getwd())
MSE.dir   <- file.path(Base.dir, "Scripts")
Data.dir  <- file.path(Base.dir,"data")              
RData.dir <- "C:/TEMP/WHOM_2022/run"
Res.dir   <- file.path(Base.dir, "Results")
stats.dir <- file.path(Res.dir, "Stats")

Source.dir <- file.path(Base.dir,"R")              #R functions
source(file.path(Source.dir,"utilities.R"))

# Rebuilding threshold
rebuiltThreshold <- 0.5

file.list <- list.files(path=stats.dir, pattern="_Stats", full.names=TRUE) 
# file.list <- file.list[grepl("_SS_", file.list)]

# manual fixing of units
my_units <- data.frame(
  perfstat = c("stock","fbar","catch","rec",     "tac", "pblim", "precbpa", "iav"),
  unit2     = c(   "kt","F(1-10)",   "kt","billions", "kt", "proportion","proportion", "proportion change"),
  stringsAsFactors = FALSE)

# print(file.list)
i <- 1

df <- data.frame(stringsAsFactors = FALSE)
for (i in 1:length(file.list)) {
  print(file.list[i])
  df <- bind_rows(df, loadRData(file.list[i])[["df"]])
}
# df %>% filter(assess=="SS", niters==1000, iter==1) %>% View()

ass <-
  bind_rows(
    loadRData("C:/DATA/GIT/homrebuild/MSEInitialisation/WGWIDE22/RData/WHOM_SS22_FLS_WGWIDE.RData") %>% as.data.frame() %>% mutate(assess="SS"),
    
  )

# COULD BE DONE IN SIMULATION CODE
df <- 
  df %>%  
  
  filter(niters==1000) %>% 
  # mutate(method = sifelse(is.na(method),"EQSIM", method)) %>% 
  mutate(method = "EQSIM") %>%
  mutate(assessyear = 2022) %>% 
  
  # mutate(period = ifelse(is.na(period) & year <= (an(assessyear)), "HI",period)) %>% 
  mutate(period = ifelse(an(year) < an(assessyear), "HI",period) ) %>% 
  mutate(ftgt = ac(ftgt)) %>% 
  
  left_join(my_units, by="perfstat") %>% 
  
  mutate(
    mean   = ifelse(perfstat == "stock", mean/1000, mean),
    median = ifelse(perfstat == "stock", median/1000, median),
    lower  = ifelse(perfstat == "stock", lower/1000, lower),
    upper  = ifelse(perfstat == "stock", upper/1000, upper),
    data   = ifelse(perfstat == "stock", data/1000, data),
  ) %>% 
  mutate(
    blim      = ifelse(perfstat == "stock", blim/1000, NA),
    bpa       = ifelse(perfstat == "stock", bpa/1000, NA),
    msybtrig  = ifelse(perfstat == "stock", bpa/1000, NA)
  ) %>%  
  
  mutate(
    mean   = ifelse(perfstat == "rec", mean/1000000, mean),
    median = ifelse(perfstat == "rec", median/1000000, median),
    lower  = ifelse(perfstat == "rec", lower/1000000, lower),
    upper  = ifelse(perfstat == "rec", upper/1000000, upper),
    data   = ifelse(perfstat == "rec", data/1000000, data)
  ) %>% 

  mutate(
    mean   = ifelse(perfstat == "catch", mean/1000, mean),
    median = ifelse(perfstat == "catch", median/1000, median),
    lower  = ifelse(perfstat == "catch", lower/1000, lower),
    upper  = ifelse(perfstat == "catch", upper/1000, upper),
    data   = ifelse(perfstat == "catch", data/1000, data)
  ) 


# save(df, file="df.RData")

# ========================================================================================================

# plotvar function

# mystock      = "WHOM"
# myassess     = c("SS", "SAM")
# myassessyear = c("2022")
# mymethod     = c("EQSIM")
# myom         = c("OM2.3", "OM2.5")
# myniters     = 1000
# mymp         = c("MP5.23")
# mynyrs       = 23
# myftgt       = c(0.074)
# myperfstat   = c("stock", "fbar","rec", "catch")
# mycolour     = "blue"
# myyintercept = "blim"
# myvalue      = "median"
# myfacets     = c("perfstat", "assess")
# myfirstyear  = 2015
# mylastyear   = 2025
# scale_y_free = TRUE
# add_assessment = TRUE

plotvar <- function(mystock      =  "WHOM",
                    myassess     = "SAM",
                    myassessyear = c("2019","2020"),
                    mymethod  = "EQSIM",
                    myom         = c("OM2.4","OM2.5"),
                    myniters     = "1000",
                    mymp         = c("MP5.23"),
                    mynyrs       = "23",
                    myftgt       = ac(c(0.0, 0.025, 0.05, 0.075, 0.10, 0.125, 0.15)),
                    myperfstat   = "stock",
                    mycolour     = "blue",
                    myyintercept = "blim",
                    myvalue      = "median",
                    myfacets     = c("assessyear","ftgt"),
                    myfirstyear  = as.numeric(NA),
                    mylastyear   = as.numeric(NA),
                    scale_y_free = FALSE,
                    add_assessment = FALSE) {
  
  
  # history
  h <-
    df %>% 
    filter(period     %in% c("HI")) %>% 
    filter(perfstat   %in% myperfstat) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method     %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    # filter(nyrs       %in% mynyrs) %>% 
    filter(ftgt       %in% ac(myftgt)) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>%   
    
    mutate(age = as.numeric(age)) 

  # future
  d <- 
    df %>%
    filter(period     %in% c("CU","ST","MT",'LT')) %>% 
    filter(perfstat   %in% myperfstat) %>% 
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method  %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>%
    # filter(nyrs       %in% mynyrs) %>% 
    filter(ftgt       %in% ac(myftgt)) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>%   
    
    mutate(age  = as.numeric(age)) 
    
  # periods
  p <-
    bind_rows(h, d) %>% 
    distinct(assessyear, period, year) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>%   
    
    group_by(assessyear, period) %>% 
    summarise(
      minyear = min(year),
      maxyear = max(year)
    )
  
  # intercept
  if(!all(is.na(myyintercept))) {
    i <-
      h %>% 
      distinct(perfstat, y=get(myyintercept)) %>% 
      drop_na() 
  } else {
    i <- an(NA)
  }

  # title
  t <- paste(
    toupper(myperfstat),
    toupper(mystock),
    paste(unique(myassess), collapse="-"),
    paste(unique(myassessyear), collapse="-"),
    paste(unique(mymethod), collapse="-"),
    paste(unique(myom), collapse="-"),
    paste(unique(mymp), collapse="-"),
    sep="_"
  )
  
  # h %>% filter(!is.na(iter), !is.na(data)) %>% View()
  
  myfig <- 

    ggplot(d, aes(x=year, y=get(myvalue), group=mp)) +
    theme_publication() +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5)) +
    theme( panel.grid.major.x = element_blank()) +
    theme(legend.position = "none") +
    theme(panel.spacing = unit(0.2, "lines")) +
    
    # historical ribbon
    geom_ribbon(data=filter(h, !is.na(get(myvalue))),
                aes(ymin=lower, ymax=upper, group=iter), alpha=0.4, fill="gray") +
    
    # historical worms
    geom_line(data=filter(h, metric=="worm"),
              aes(x=year, y=data, group=iter), colour="darkgray", size=0.5) +
    
    # historical median
    geom_line(data=filter(h, !is.na(get(myvalue))),
              aes(x=year,y=get(myvalue),group=iter), colour="black", size=1) +
    
    # historical assessment
    {if(add_assessment) geom_line(data=filter(h, iter==1),
              aes(x=year,y=data,group=iter), colour="red", size=1)} +
    
    # future ribbon
    geom_ribbon(data=filter(d, !is.na(get(myvalue))),
                aes(ymin=lower, ymax=upper, group=iter, fill=perfstat), alpha=0.4) +
    
    # future worms
    geom_line(data=filter(d, metric=="worm"),
              aes(x=year, y=data, group=iter, colour=perfstat), size=0.5) +
    
    # future median
    geom_line(data=filter(d, !is.na(get(myvalue))),
              aes(x=year,y=get(myvalue),group=iter, colour=perfstat), size=1) +
    
    # hline
    {if(!all(is.na(myyintercept))) geom_hline(data=i,
                                              aes(yintercept=y), linetype="dashed")}  +
    
    # vertical lines (periods)
    geom_vline(data=filter(p, period=="CU"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="ST"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="MT"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="LT"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="LT"),
               aes(xintercept=maxyear), linetype="dotted") +
    
    expand_limits(y=0) +
    labs(x="", y=myperfstat, title=t) +

    {if(scale_y_free==TRUE) {
      facet_grid(get(myfacets[1]) ~ get(myfacets[2]), scales="free_y")
    } else {
      facet_grid(get(myfacets[1]) ~ get(myfacets[2]))
    }}
    
  print(myfig)
  
  ggsave(file = file.path(Res.dir,paste0(t, " summaryplot.png")),
         device="png", width = 30, height = 20, units = "cm")

}

# ========================================================================================================

# plotrecovery

# mystock      = "WHOM"
# myassess     = "SAM"
# myassessyear = c("2022")
# mymethod     = c("EQSIM")
# myom         = c("OM2.5")
# mymp         = c("MP5.23")
# myftgt       = c(0.001, 0.05, 0.075, 0.10, 0.15)
# myfacets     = c("mp","ftgt")
# myfirstyear  = 2005
# mylastyear   = max(df$year)
# myintercept  = 0.5

plotrecovery <- function(
                    mystock      =  "WHOM",
                    myassess     = "SAM",
                    myassessyear = c("2019","2020"),
                    mymethod     = "EQSIM",
                    myom         = c("OM2.4","OM2.5"),
                    mymp         = c("MP5.23"),
                    myftgt       = c(0.0, 0.025, 0.05, 0.075, 0.10, 0.125, 0.15),
                    myintercept  = 0.5,
                    myfacets     = c("assessyear","ftgt"),
                    myfirstyear  = as.numeric(NA),
                    mylastyear   = as.numeric(NA)) {
  
  # plot recovery to blim and bpa
  d <-
    df %>%
    filter(perfstat %in% c("precblim","precbpa")) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method  %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    filter(ftgt       %in% myftgt) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} 
  
  # lines
  p <-
    df %>%
    filter(perfstat %in% c("firstyearrebuildtoblim","firstyearrebuildtobpa")) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method  %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    filter(ftgt       %in% myftgt) %>% 
    
    mutate(perfstat = case_when(
      perfstat == "firstyearrebuildtoblim" ~ "precblim",
      perfstat == "firstyearrebuildtobpa"  ~ "precbpa",
      TRUE                                 ~ perfstat
    ))

  # title
  t <- paste(
    "RECOV",
    toupper(mystock),
    paste(unique(myassess), collapse="-"),
    paste(unique(myassessyear), collapse="-"),
    paste(unique(mymethod), collapse="-"),
    paste(unique(myom), collapse="-"),
    paste(unique(mymp), collapse="-"),
    sep="_"
  )
  
  myfig <-
    d %>% 
    ggplot(aes(x=year, y=mean, group=perfstat)) +
    theme_publication() +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5)) +
    theme( panel.grid.major.x = element_blank()) +
    
    geom_vline(data=p, aes(xintercept=mean, colour=perfstat), linetype="dashed") +

    geom_hline(yintercept=myintercept, colour="gray", linetype="dashed") +
    
    geom_text(data=filter(p, perfstat %in% c("precblim")),
              aes(x=mean, label=ac(mean), colour=perfstat),
              y=1.0, vjust=1, hjust=0, nudge_x = 1, size=3) +
    
    geom_text(data=filter(p, perfstat %in% c("precbpa")),
              aes(x=mean, label=ac(mean), colour=perfstat),
              y=0.0, vjust=0, hjust=0, nudge_x = 1, size=3) +
    
    geom_line(aes(colour=perfstat)) +
    
    expand_limits(y=0) +
    labs(x="", y="", title=t) +
    facet_grid(get(myfacets[1]) ~ get(myfacets[2])) 
  
  print(myfig)
  
  # ggsave(file = file.path(Res.dir,paste0(t, " recoveryplot.png")),
  #        device="png", width = 30, height = 20, units = "cm")
  
  
} # end of plotrecovery

# ========================================================================================================

# plot prob above blim

plotpblim <- function(
                    mystock      =  "WHOM",
                    myassess     = "SAM",
                    myassessyear = c("2019","2020"),
                    mymethod     = "EQSIM",
                    myom         = c("OM2.4","OM2.5"),
                    mymp         = c("MP5.23"),
                    myftgt       = c(0.0, 0.025, 0.05, 0.075, 0.10, 0.125, 0.15),
                    myfacets     = c("assessyear","ftgt"),
                    myfirstyear  = as.numeric(NA),
                    mylastyear   = as.numeric(NA) ) {
  
  # plot probability below blim and bpa
  d <-
    df %>%
    filter(perfstat   %in% c("pblim")) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method     %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    filter(ftgt       %in% myftgt) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} 
  
  # periods
  p <-
    d %>% 
    distinct(assessyear, period, year) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>%   
    
    group_by(assessyear, period) %>% 
    summarise(
      minyear = min(year),
      maxyear = max(year)
    )
  
  # title
  t <- paste(
    "pBlim",
    toupper(mystock),
    paste(unique(myassess), collapse="-"),
    paste(unique(myassessyear), collapse="-"),
    paste(unique(mymethod), collapse="-"),
    paste(unique(myom), collapse="-"),
    paste(unique(mymp), collapse="-"),
    sep="_"
  )
  
  myfig <-
    d %>% 
    ggplot(aes(x=year, y=mean, group=perfstat)) +
    theme_publication() +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5)) +
    theme( panel.grid.major.x = element_blank()) +
    
    geom_hline(yintercept=0.05, colour="gray", linetype="dashed") +
    
    geom_line(aes(colour=perfstat)) +
    
    # vertical lines (periods)
    geom_vline(data=filter(p, period=="CU"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="ST"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="MT"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="LT"),
               aes(xintercept=minyear), linetype="dotted") +
    geom_vline(data=filter(p, period=="LT"),
               aes(xintercept=maxyear), linetype="dotted") +

    expand_limits(y=0) +
    labs(x="", y="", title=t) +
    facet_grid(get(myfacets[[1]]) ~ get(myfacets[[2]])) 
  
  print(myfig)
  
  ggsave(file = file.path(Res.dir,paste0(t, " pblimplot.png")),
         device="png", width = 30, height = 20, units = "cm")
  
  
} # end of plotpblim



# ========================================================================================================

# plotscenario

# mystock      =  "WHOM"
# myassess     = "SS3"
# myassessyear = c("2020")
# mymethod     = "EQSIM"
# myom         = c("OM2.3")
# mymp         = c("MP5.23")
# myftgt       = c(0.075)
# myfacets     = c("perfstat")
# myfirstyear  = 2000
# mylastyear   = as.numeric(NA)
# myperfstat   = c("stock","fbar", "pblim", "precbpa")
# mycolours    = c("red","blue","green", "blue")

# mystock      =  "WHOM"
# myassess     = "SS3"
# myassessyear = c("2020")
# mymethod     = "EQSIM"
# myom         = c("OM2.3")
# mymp         = c("MP5.23")
# myftgt       = c("0.074")
# myfacets     = c("perfstat")
# myfirstyear  = 2000
# mylastyear   = as.numeric(NA)
# myperfstat   = c("fbar")
# mycolours    = c("blue")
# mylastyear   = as.numeric(NA)

plotscenario <- function(
                    mystock      =  "WHOM",
                    myassess     = "SAM",
                    myassessyear = c("2022"),
                    mymethod     = "EQSIM",
                    myom         = c("OM2.5"),
                    mymp         = c("MP5.25"),
                    myftgt       = c(0.075),
                    myfacets     = c("perfstat"),
                    myfirstyear  = as.numeric(NA),
                    mylastyear   = as.numeric(NA),
                    myperfstat   = c("stock","pblim"),
                    mycolours    = rep(c("red","blue","green", "blue"),5),
                    showtitle    = FALSE) {
  
  # history
  h <-
    df %>% 
    # filter(period     %in% c("HI")) %>% 
    filter(perfstat   %in% myperfstat) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method  %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>%
    filter(ftgt       %in% myftgt) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>% 
    
    mutate(age = as.numeric(age)) 

  # future
  d <- 
    df %>%
    filter(period     %in% c("CU","ST","MT",'LT')) %>% 
    filter(perfstat   %in% myperfstat) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method  %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    filter(ftgt       %in% myftgt) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>% 
    
    mutate(age  = as.numeric(age)) 
    
  # periods
  p <-
    bind_rows(h, d) %>% 
    distinct(assessyear, period, year) %>% 
    
    {if(!is.na(myfirstyear)) filter(., year >= myfirstyear) else (.)} %>%    
    {if(!is.na(mylastyear))  filter(., year <= mylastyear) else (.)} %>%   
    
    group_by(assessyear, period) %>% 
    summarise(
      minyear = min(year),
      maxyear = max(year)
    )

  # units
  u <-
    d %>% 
    distinct(perfstat, unit2)
  
  # reference points
  rp <-
    d %>% 
    distinct(perfstat, blim, bpa, msybtrig, fmsy, flow, ftgt)
  
  # View(rp)
  
  # firstyear pblim
  p1 <-
    df %>% 
    filter(perfstat   %in% c("pblim")) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method     %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    filter(ftgt       %in% myftgt) %>% 
    filter(!period    %in% c("HI")) %>%
    filter(mean       < 0.05) %>% 
    
    group_by(perfstat, stock, assess, assessyear, method, om, mp, ftgt) %>% 
    summarise(mean = min(year, na.rm=TRUE))
    
    
  # recoverylines
  p2 <-
    df %>%
    filter(perfstat %in% c("firstyearrebuildtobpa")) %>%
    filter(stock      %in% mystock) %>% 
    filter(assess     %in% myassess) %>% 
    filter(assessyear %in% myassessyear) %>% 
    filter(method     %in% mymethod) %>% 
    filter(om         %in% myom) %>% 
    filter(mp         %in% mymp) %>% 
    filter(ftgt       %in% myftgt) %>% 
    
    mutate(perfstat = case_when(
      perfstat == "firstyearrebuildtoblim" ~ "precblim",
      perfstat == "firstyearrebuildtobpa"  ~ "precbpa",
      TRUE                                 ~ perfstat
    ))
  
  # title
  t <- paste(
    toupper(mystock),
    paste(unique(myassess), collapse="-"),
    paste(unique(myassessyear), collapse="-"),
    paste(unique(mymethod), collapse="-"),
    paste(unique(myom), collapse="-"),
    paste(unique(mymp), collapse="-"),
    sep="_"
  )
  
  plist <- list(NULL)
  i <- 1
  for (i in 1:length(myperfstat)) {
    if(myperfstat[[i]] %in% c("stock","fbar","catch","rec","tac", "iav")) {
      
      print(i)
      
      plist[[i]] <-
        
        ggplot(data=filter(d, perfstat==myperfstat[[i]]), 
               aes(x=year, y=mean, group=perfstat)) +
        theme_publication() +
        theme(plot.margin = unit(c(0,0,0,0), "cm")) +
        theme(legend.position="none") +
        theme( panel.grid.major.x = element_blank()) +
        theme(strip.text = element_text(size = 12)) +
        
        {if (i == length(myperfstat)) 
          theme(axis.text.x = element_text(angle = 90, vjust=0.5)) else 
            theme(axis.text.x = element_blank()) } +
        
        # historical ribbon
        geom_ribbon(data=filter(h, !is.na(mean), perfstat==myperfstat[[i]]),
                    aes(ymin=lower, ymax=upper, group=iter), alpha=0.4, fill="gray") +
        
        # historical worms
        geom_line(data=filter(h, metric=="worm", perfstat==myperfstat[[i]]),
                  aes(x=year, y=data, group=iter), colour="darkgray", size=0.3) +
        
        # historical median
        geom_line(data=filter(h, !is.na(median), perfstat==myperfstat[[i]]), 
                  aes(x=year,y=median, group=iter), colour="black", size=1.5) +
    
        # future ribbon
        geom_ribbon(data=filter(d, !is.na(median), perfstat==myperfstat[[i]]),
                    aes(ymin=lower, ymax=upper, group=iter), alpha=0.3, fill=mycolours[[i]]) +
        
        # future worms
        geom_line(data=filter(d, metric=="worm", perfstat==myperfstat[[i]]),
                  aes(x=year, y=data, group=iter), colour=mycolours[[i]], size=0.3) +
        
        # future median
        geom_line(data=filter(d, !is.na(median), perfstat==myperfstat[[i]]),
                  aes(x=year,y=median,group=iter), colour=mycolours[[i]], size=1.5) +
        
        # vertical lines (periods)
        geom_vline(data=filter(p, period=="CU"),
                   aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="ST"),
        #            aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="MT"),
        #            aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="LT"),
        #            aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="LT"),
        #            aes(xintercept=maxyear), linetype="dotted") +
    
        # horizontal lines (reference points)
        {if (myperfstat[[i]] == "stock") geom_hline(aes(yintercept=blim), linetype="dashed") } +
        {if (myperfstat[[i]] == "stock") geom_text(data=filter(rp, perfstat=="stock"), 
                                                   aes(y=blim), label="blim", x=myfirstyear,
                                                   vjust=0, hjust=0, inherit.aes = FALSE) } +
        
        {if (myperfstat[[i]] == "stock") geom_hline(aes(yintercept=bpa), linetype="dotted") } +
        {if (myperfstat[[i]] == "stock") geom_text(data=filter(rp, perfstat=="stock"), 
                                                   aes(y=bpa), label="bpa", x=myfirstyear, 
                                                   vjust=0, hjust=0, inherit.aes = FALSE) } +
        
        {if (myperfstat[[i]] == "fbar") geom_hline(aes(yintercept=as.numeric(ftgt)), linetype="dashed") } +
        {if (myperfstat[[i]] == "fbar") geom_text(data=filter(rp, perfstat=="fbar"), 
                                                  aes(y=as.numeric(ftgt)), label="ftgt", x=myfirstyear, 
                                                   vjust=0, hjust=0, inherit.aes = FALSE) } +

        expand_limits(y=0) +
        
        scale_x_continuous(breaks=seq(min(h$year), max(d$year), 5)) +
        
        labs(x="", y = filter(u, perfstat == myperfstat[[i]])$unit2) +
        {if(i==1 & showtitle==TRUE) labs(title=t)} +
        
        facet_grid( perfstat ~ .)
      
  
    } else if (myperfstat[i] %in% c("pblim")) {
      
      print(i)
           
      plist[[i]] <-
        ggplot(data=filter(d, perfstat==myperfstat[[i]]), 
                   aes(x=year, y=mean, group=perfstat)) +
        theme_publication() +
        theme(plot.margin = unit(c(0,0,0,0), "cm")) +
        theme(legend.position="none") +
        theme( panel.grid.major.x = element_blank()) +
        theme(strip.text = element_text(size = 12)) +
        {if (i == length(myperfstat)) theme(axis.text.x = element_text(angle = 90, vjust=0.5)) else theme(axis.text.x = element_blank()) } +
        
        geom_hline(yintercept=0.05, colour="gray", linetype="dashed") +
        
        geom_vline(data=p1, aes(xintercept=mean), colour=mycolours[[i]], linetype="dashed") +
        geom_text(data= p1,
                  aes(x=mean, label=ac(mean)),
                  y=0.05, vjust=0, hjust=0, nudge_x = 0.2, colour=mycolours[[i]]) +
        
        geom_line(data=filter(h, perfstat == myperfstat[[i]]), colour="gray", size=1) +
        geom_line(colour=mycolours[[i]], size=1) +
        
        # vertical lines (periods)
        geom_vline(data=filter(p, period=="CU"),
                   aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="ST"),
        #            aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="MT"),
        #            aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="LT"),
        #            aes(xintercept=minyear), linetype="dotted") +
        # geom_vline(data=filter(p, period=="LT"),
        #            aes(xintercept=maxyear), linetype="dotted") +
    
        expand_limits(y=0) +
        scale_x_continuous(breaks=seq(min(h$year), max(d$year), 5)) +
        
        labs(x="", y = filter(u, perfstat == myperfstat[[i]])$unit2) +
        {if(i==1 & showtitle==TRUE) labs(title=t)} +
        
        facet_grid( perfstat ~ .)
  
    } else if (myperfstat[i] %in% c("precbpa")) {
      
      print(i)
           
      plist[[i]] <-
        ggplot(data=filter(d, perfstat==myperfstat[[i]]), 
                   aes(x=year, y=mean, group=perfstat)) +
        theme_publication() +
        theme(plot.margin = unit(c(0,0,0,0), "cm")) +
        theme(legend.position="none") +
        theme( panel.grid.major.x = element_blank()) +
        theme(strip.text = element_text(size = 12)) +
        {if (i == length(myperfstat)) theme(axis.text.x = element_text(angle = 90, vjust=0.5)) else theme(axis.text.x = element_blank()) } +
        
        geom_vline(data=p2, aes(xintercept=mean), colour=mycolours[[i]], linetype="dashed") +
        
        geom_hline(yintercept=0.5, colour="gray", linetype="dashed") +
        
        geom_vline(data=filter(p, period=="CU"),
                   aes(xintercept=minyear), linetype="dotted") +
        
        geom_text(data=filter(p2, perfstat %in% c("precbpa")),
                  aes(x=mean, label=ac(mean)),
                  y=0.0, vjust=0, hjust=0, nudge_x = 0.2, colour=mycolours[[i]]) +
    
        geom_line(colour=mycolours[[i]], size=1) +

        expand_limits(y=0, x=min(p$minyear)) +
        scale_x_continuous(breaks=seq(min(h$year), max(d$year), 5)) +
        
        labs(x="", y = filter(u, perfstat == myperfstat[[i]])$unit2) +
        {if(i==1 & showtitle==TRUE) labs(title=t)} +
        
        facet_grid( perfstat ~ .)

    } # end of if statements
  
  } # end of for loop

print(patchwork::wrap_plots(plist) + 
  patchwork::plot_layout(ncol = 1) +
  patchwork::plot_annotation() & theme(plot.tag = element_text(size = 8)))

ggsave(file = file.path(Res.dir,paste0(t, paste(myperfstat, collapse="_")," scenarioplot.png")),
       device="png", width = 30, height = 20, units = "cm")

  
} # end of function



```

*Working document for WKWHMRP 2021*


Martin Pastoors, `r format(Sys.time(), '%d/%m/%Y')`

&nbsp;  

**Abstract**

```{r echo=FALSE, fig.align="center", fig.asp=1.2, message=FALSE, warning=FALSE}

plotvar(mystock      = "WHOM",
        myassess     = c("SS", "SAM"),
        myassessyear = c("2022"),
        mymethod     = c("EQSIM"),
        myom         = c("OM2.3", "OM2.5"),
        mymp         = c("MP5.23"),
        myftgt       = c(0.074),
        myperfstat   = c("stock", "fbar","rec", "catch"),
        mycolour     = "blue",
        myyintercept = "blim",
        myvalue      = "median",
        myfacets     = c("perfstat", "assess"),
        myfirstyear  = 2015,
        mylastyear   = 2025,
        scale_y_free = TRUE,
        add_assessment = TRUE)


```
_fig x Simulation summary 2022 assessment, SS3, EqSim. MP5.23 double breakpoint F with 20% IAV constraint above Btrigger. _

\newpage

```{r echo=FALSE, fig.align="center", fig.asp=0.5, message=FALSE, warning=FALSE}

plotpblim (  mystock      = "WHOM",
             myassess     = c("SS", "SAM"),
             myassessyear = c("2022"),
             mymethod     = c("EQSIM"),
             myom         = c("OM2.3", "OM2.5"),
             mymp         = c("MP5.23"),
             myftgt       = c(0.074),
             myfacets     = c("om","assess"),
             myfirstyear  = 2005)

```

\newpage

```{r echo=FALSE, fig.align="center", fig.asp=0.55, message=FALSE, warning=FALSE}


plotrecovery(mystock      = "WHOM",
             myassess     = "SS",
             myassessyear = c("2022"),
             mymethod     = c("EQSIM"),
             myom         = c("OM2.3"),
             mymp         = c("MP5.23"),
             myftgt       = c(0.001, 0.05, 0.074, 0.10, 0.15),
             myfacets     = c("mp","ftgt"),
             myfirstyear  = 2005,
             mylastyear   = max(df$year),
             myintercept  = 0.5)

```


```{r echo=FALSE, fig.align="center", fig.asp=0.55, message=FALSE, warning=FALSE}


t <-
  df %>% 
  filter(mp %in% c("MP5.23")) %>% 
  filter(assess %in% c("SS")) %>%  
  filter(perfstat %in% c("catch","stock", "fbar", "pblim", "pbpa")) %>%
  filter(ftgt %in% c("0.001", "0.05", "0.074", "0.1", "0.15")) %>% 
  filter(year >= 2023) %>%
  filter(year <= 2030) %>% 
  filter(!is.na(median) | !is.na(mean)) %>% 
  mutate(median = ifelse(perfstat %in% c("catch", "stock"), 1000*median, median))


t %>% 
  filter(perfstat=="catch") %>% 
  reshape2::dcast(perfstat+ftgt ~ year, value.var="median", sum, margins=c("year")) %>% 
  ungroup() %>% 
  pander::pandoc.table(., 
               style        = "simple",
               split.tables = 200, 
               split.cells  = c(rep(7,10)),
               justify      = "right",
               missing      = " ",
               big.mark     = ',', 
               round        = c(0))

t %>% 
  filter(perfstat=="stock") %>% 
  reshape2::dcast(perfstat+ftgt ~ year, value.var="median", sum, margins=NA) %>% 
  ungroup() %>% 
  pander::pandoc.table(., 
               style        = "simple",
               split.tables = 200, 
               split.cells  = c(rep(7,10)),
               justify      = "right",
               missing      = " ",
               big.mark     = ',', 
               round        = c(0))


t %>% 
  filter(perfstat=="fbar") %>% 
  reshape2::dcast(perfstat+ftgt ~ year, value.var="median", sum, margins=NA) %>% 
  ungroup() %>% 
  pander::pandoc.table(., 
               style        = "simple",
               split.tables = 200, 
               split.cells  = c(rep(7,10)),
               justify      = "right",
               missing      = " ",
               big.mark     = ',', 
               round        = c(3))

t %>% 
  filter(perfstat=="pblim") %>% 
  reshape2::dcast(perfstat+ftgt ~ year, value.var="mean", sum, margins=NA) %>% 
  ungroup() %>% 
  pander::pandoc.table(., 
               style        = "simple",
               split.tables = 200, 
               split.cells  = c(rep(7,10)),
               justify      = "right",
               missing      = " ",
               big.mark     = ',', 
               round        = c(2))

t %>% 
  filter(perfstat=="pbpa") %>% 
  reshape2::dcast(perfstat+ftgt ~ year, value.var="mean", sum, margins=NA) %>% 
  ungroup() %>% 
  pander::pandoc.table(., 
               style        = "simple",
               split.tables = 200, 
               split.cells  = c(rep(7,10)),
               justify      = "right",
               missing      = " ",
               big.mark     = ',', 
               round        = c(2))

```

